name: Sync Scripts

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # 使用配置的 token
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run sync script
      run: python sync.py
        
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update scripts - $(date)"; git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
